language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t pmacdougall/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pmacdougall/react-test npm test

after_success:
  - docker build -t pmacdougall/multi-client ./client
  - docker build -t pmacdougall/multi-nginx ./nginx
  - docker build -t pmacdougall/multi-server ./server
  - docker build -t pmacdougall/multi-worker ./worker

  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push images to docker hub
  - docker push pmacdougall/multi-client
  - docker push pmacdougall/multi-nginx
  - docker push pmacdougall/multi-server
  - docker push pmacdougall/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-863118476981'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
